/*
 * Seed name table.
 */

exports.seed = function(db) {

  [
    "Arquette", "Arthur", "Ayres", "Bailey", "Baker", "Banks",
    "Barker", "Barnes", "Barnett", "Barr", "Barry", "Barton",
    "Bates", "Bauer", "Beatty", "Beck", "Becker", "Bell",
    "Bellamy", "Benedict", "Benjamin", "Bennett", "Bentley",
    "Berg", "Bergen", "Best", "Billings", "Birmingham",
    "Black", "Blue", "Bond", "Booth", "Bowen", "Boyd",
    "Bradley", "Bradshaw", "Brandenburg", "Bridges", "Brill",
    "Brooks", "Brown", "Browne", "Bruce", "Bruno", "Bryant",
    "Burke", "Burns", "Butler", "Byrd", "Byron", "Cagney",
    "Cameron", "Campbell", "Cannon", "Carey", "Carpenter",
    "Carroll", "Carson", "Carter","Caruso", "Casey",
    "Cassavetes", "Castle", "Chan", "Chandler", "Chaney",
    "Chapin", "Chaplin", "Chapman", "Chase", "Chester", "Cho",
    "Christopher", "Church", "Clark", "Clarke", "Clay",
    "Clifton", "Cline", "Coffey", "Cohen", "Cole", "Coleman",
    "Collins", "Conklin", "Conley", "Connelly", "Connor",
    "Conway", "Cook", "Cooper", "Coppola", "Corbett", "Corey",
    "Corley", "Corrigan", "Craig", "Crane", "Craven",
    "Crawford", "Crockett", "Crosby", "Cross", "Culp",
    "Curtis", "Dalton", "Damon", "Daniels", "Davidson",
    "Davis", "Day", "Dean", "DeBoy", "Delaney", "DeLuise",
    "Denton", "Devlin", "Dexter", "Diamond", "Dillon",
    "Dinehart", "Dobson", "Dolenz", "Donaldson", "Donovan",
    "Doucette", "Douglas", "Drake", "Draper", "Drew", "Duke",
    "Duncan", "Dunlap", "Dunn", "Duval", "Dye", "Dyke",
    "Eaton", "Eberle", "Edwards", "Elliott", "Ellis",
    "Ellison", "Estes", "Estevez", "Evans", "Farley",
    "Farnum", "Farrell", "Faulkner", "Fenton", "Ferguson",
    "Field", "Finnegan", "Finnerty", "Fisher", "Fitzpatrick",
    "Fleming", "Flynn", "Ford", "Forman", "Forrest", "Foster",
    "Frank", "Franklin", "Freeman", "French", "Gabriel",
    "Gallagher", "Gamble", "Gargan", "Garrett", "Gaston",
    "Geary", "George", "Gilbert", "Ginty", "Glazer",
    "Gleason", "Goldberg", "Goodman", "Gorcey", "Gordon",
    "Gorman", "Gould", "Graham", "Grant", "Graves", "Gray",
    "Green", "Greene", "Griffin", "Griffith", "Grillo",
    "Grimes", "Gunn", "Hackett", "Haggerty", "Hale", "Haley",
    "Hall", "Hampton", "Hansen", "Hanson", "Hardy", "Harmon",
    "Harper", "Harris", "Harrison", "Harron", "Hart",
    "Harvey", "Hatton", "Hayden", "Hedlund", "Henry",
    "Hickman", "Hicks", "Higgins", "Hill", "Hindman", "Hines",
    "Hoffman", "Holland", "Holmes", "Holt", "Holtz",
    "Hopkins", "Hopper", "Houston", "Howard", "Howe",
    "Hughes", "Hull", "Humphrey", "Hunt", "Hurst", "Huston",
    "Hutton", "III", "Irving", "Jackson", "Jacobs", "James",
    "Janney", "Jenkins", "Jensen", "John", "Johnson",
    "Johnston", "Jones", "Jordan", "Jr.", "Kane", "Kassen",
    "Keith", "Kelly", "Kemper", "Kendall", "Kent", "King",
    "Kramer", "Lambert", "Lane", "Lee", "Leonard", "LeRoy",
    "Lewis", "Lincoln", "Lloyd", "Lucas", "Lund", "MacDonald",
    "Mack", "MacQuarrie", "Mann", "Marcus", "Marion",
    "Martin", "Martini", "Martino", "Marx", "Mason",
    "Maynard", "McAllister", "McCoy", "McCullough",
    "McDermott", "McGregor", "McGuire", "McKee", "McKinney",
    "McQueen", "McRae", "McWade", "McVey", "Mead", "Meeker",
    "Meredith", "Meyer", "Meyers", "Michael", "Middleton",
    "Miller", "Mills", "Miner", "Minor", "Mitchell",
    "Mitchum", "Mohr", "Monroe", "Montana", "Monty", "Moore",
    "Moran", "Morgan", "Morris", "Morrison", "Morrow",
    "Morse", "Morton", "Moseley", "Moses", "Mosley", "Moss",
    "Murdock", "Murphy", "Murray", "Myers", "Nagel",
    "Naughton", "Neill", "Nelson", "Newman", "Newton",
    "Nichols", "Nicholson", "Nolan", "Norris", "North",
    "Norton", "Nugent", "O'Brien", "O'Connell", "O'Connor",
    "O'Donnell", "O'Halloran", "O'Hare", "O'Leary", "Oliver",
    "O'Neal", "O'Neill", "O'Reilly", "Ortega", "Orth",
    "Osborne", "O'Shea", "Osmond", "Pace", "Pack", "Paige",
    "Palmer", "Parker", "Parks", "Parsons", "Patrick",
    "Patten", "Patton", "Paul", "Payne", "Pearlman", "Peck",
    "Pendleton", "Penn", "Perez", "Perkins", "Perry",
    "Petersen", "Peterson", "Petrie", "Philbin", "Phillips",
    "Phoenix", "Pidgeon", "Pierce", "Pierson", "Pine",
    "Pinkston", "Pitt", "Pitts", "Piven", "Platt", "Poitier",
    "Pollard", "Porter", "Powell", "Power", "Powers", "Pratt",
    "Presley", "Preston", "Price", "Quaid", "Quinn", "Ramsey",
    "Rankin", "Rasuk", "Ray", "Reaves", "Reed", "Reeves",
    "Reid", "Reilly", "Reiner", "Rey", "Reynolds", "Rice",
    "Rich", "Richards", "Richardson", "Richman", "Richmond",
    "Ridgely", "Riley", "Riordan", "Robbins", "Roberts",
    "Robins", "Robinson", "Rocco", "Rock", "Rodriguez",
    "Rodríguez", "Rogers", "Romano", "Romero", "Rosenberg",
    "Ross", "Rossi", "Roth", "Rowland", "Roy", "Rubin",
    "Ruiz", "Russell", "Russo", "Ryan", "Ryder", "Sanders",
    "Santos", "Sargent", "Savage", "Schilling", "Schmidt",
    "Schneider", "Schulze", "Schwartz", "Schwartzman",
    "Scorsese", "Scott", "Segal", "Seymour", "Shaffer",
    "Shaw", "Shea", "Shearer", "Sheffield", "Shepherd",
    "Sheridan", "Sherman", "Shields", "Showalter", "Silva",
    "Silver", "Silverman", "Simmons", "Simpson", "Sinclair",
    "Singer", "Sisto", "Slattery", "Smith", "Snyder",
    "Sommer", "Space", "Spano", "Spencer", "Stack", "Stahl",
    "Stanford", "Stanley", "Stanton", "Stark", "Steadman",
    "Steele", "Steinberg", "Stern", "Stewart", "Stevens",
    "Stevenson", "Stone", "Storch", "Storm", "Stowell",
    "Strait", "Strauss", "Striker", "Strong", "Stuart",
    "Sullivan", "Suplee", "Sussman", "Sutherland", "Sutton",
    "Sweet", "Swenson", "Swift", "Switzer", "Sylvester",
    "Taylor", "Tenney", "Terry", "Thomas", "Thompson",
    "Tierney", "Todd", "Tom", "Travis", "Tucci", "Tucker",
    "Turk", "Turner", "Turturro", "Wagner", "Wahlberg",
    "Waite", "Valentine", "Walker", "Wall", "Wallace",
    "Walsh", "Walton", "Wang", "Ward", "Warde", "Vargas",
    "Warren", "Washington", "Waters", "Watson", "Vaughn",
    "Wayans", "Wayne", "Weatherly", "Weaver", "Webb",
    "Webber", "Weber", "Weisman", "Weiss", "Weller", "Welles",
    "Wells", "Ventimiglia", "Vernon", "West", "Westbrook",
    "Whalen", "Whaley", "Wheaton", "Whitaker", "White",
    "Whitfield", "Wilbur", "Wilcox", "Williams", "Williamson",
    "Willis", "Willson", "Wilson", "Vincent", "Winter",
    "Winters", "Wise", "Vogel", "Wolfe", "Wong", "Wood",
    "Woods", "Wooley", "Woolsey", "Worth", "Wright", "Wu",
    "Wyatt", "Wynn", "Yang", "York", "Yost", "Young"
  ].forEach(function(name) {
    db.run(
      "INSERT OR IGNORE INTO name ( name, type )\
       VALUES (?, ?)",
      [name, "lastname"]
    );
  });

  [
    "Aaron", "Abner", "Abraham", "Adam", "Al", "Alan", "Albert",
    "Alex", "Alexander", "Alfred", "Allan", "Allen", "Alphonso",
    "Andre", "Andrew", "Andy", "Anthony", "Arnold", "Art",
    "Arthur", "Ashton", "Austin", "Barney", "Barry", "Beau", "Ben",
    "Benjamin", "Benny", "Bernard", "Bert", "Biff", "Bill",
    "Billy", "Blake", "Bo", "Bob", "Bobby", "Brad", "Bradford",
    "Bradley", "Brandon", "Brendan", "Brent", "Brett", "Brian",
    "Brian Patrick", "Bruce", "Bryan", "Bryce", "Buck", "Bud",
    "Buddy", "Burt", "Cameron", "Carey", "Carl", "Carlos", "Chad",
    "Charles", "Charles B.", "Charley", "Charlie", "Chester",
    "Chick", "Chico", "Chris", "Christian", "Christopher", "Chuck",
    "Clarence", "Clark", "Claude", "Clay", "Clayton", "Clem",
    "Cliff", "Clifton", "Clyde", "Cody", "Colin", "Conor",
    "Conrad", "Craig", "Cullen", "Cyril", "Dale", "Dan", "Dana",
    "Daniel", "Danny", "Darrell", "Darren", "Dave", "David",
    "Dean", "Dee", "Del", "Dennis", "Derek", "Devon", "Dick",
    "Dominic", "Don", "Donald", "Dorothy", "Doug", "Douglas",
    "Drew", "Duane", "Duke", "Dustin", "Dwight", "Dylan", "Earl",
    "Earle", "Ed", "Eddie", "Edgar", "Edward", "Edwin", "Elliott",
    "Elmer", "Emilio", "Emmett", "Eric", "Erik", "Ernest", "Ernie",
    "Ethan", "Eugene", "Evan", "Forrest", "Frank", "Frankie",
    "Franklin", "Fred", "Frederic", "Frederick", "Fritz",
    "Gabriel", "Garrett", "Gary", "Gene", "Geoffrey", "George",
    "George B.", "George F.", "Gerald", "Gerry", "Gil", "Gilbert",
    "Glen", "Glenn", "Gordon", "Graham", "Grant", "Greg", "Gregg",
    "Gregory", "Gunnar", "Gus", "Guy", "Hal", "Harley", "Harold",
    "Harrison", "Harry", "Harvey", "Henry", "Herbert", "Herschel",
    "Hiram", "Hobart", "Howard", "Hugh", "Ian", "Ivan", "Jack",
    "Jackie", "Jackson", "Jacob", "Jake", "James", "Jared",
    "Jason", "Jay", "Jeff", "Jefferson", "Jeffrey", "Jeremy",
    "Jerome", "Jerry", "Jess", "Jesse", "Jim", "Jimmy", "J. J.",
    "Joe", "Joel", "Joey", "John", "John David", "John F.",
    "John Michael", "Johnnie", "Johnny", "John P.", "Jon", "Jonah",
    "Jonathan", "Jordan", "José", "Joseph", "Joseph D.", "Josh",
    "Joshua", "Judson", "Julian", "Junior", "Justin", "Kane",
    "Keith", "Ken", "Kenn", "Kenneth", "Kenny", "Kent", "Kevin",
    "Kurt", "Kyle", "Lance", "Larry", "Lawrence", "Lee", "Lenny",
    "Leo", "Leon", "Leonard", "Lew", "Lewis", "Liam", "Lloyd",
    "Lon", "Lonny", "Lou", "Louis", "Lucas", "Luke", "Mack",
    "Malcolm", "Marc", "Marco", "Marcus", "Mario", "Mark",
    "Mark L.", "Marlon", "Marques", "Marshall", "Martin", "Marvin",
    "Matt", "Matthew", "Maurice", "Max", "Mel", "Merrill",
    "Michael", "Michael Eric", "Michael J.", "Mickey", "Micky",
    "Mike", "Miles", "Milton", "Misha", "Mitch", "Monte", "Monty",
    "Morgan", "Nate", "Nathan", "Nathaniel", "Neal", "Ned", "Neil",
    "Nelson", "Nicholas", "Nick", "Nico", "Noah", "Noel", "Norman",
    "Oliver", "Oscar", "Otto", "Pat", "Patrick", "Paul", "Pete",
    "Peter", "Phil", "Philip", "Phillip", "Phillips", "Pierre",
    "Ralph", "Randy", "Ray", "Raymond", "Reid", "Rex", "Richard",
    "Rick", "Ricky", "Rob", "Robert", "Robert D.", "Robin", "Rod",
    "Roger", "Roland", "Ron", "Ronnie", "Rory", "Ross", "Roy",
    "Russ", "Russell", "Rusty", "Ryan", "Sam", "Sammy", "Scott",
    "Seamus", "Sean", "Sebastian", "Sergio", "Seth", "Shane",
    "Shaun", "Shawn", "Sid", "Sidney", "Simon", "Sonny", "Spencer",
    "Stan", "Stanley", "Stephan", "Stephen", "Steve", "Steven",
    "Stuart", "Taylor", "Ted", "Terrence", "Terry", "Theodore",
    "Thomas", "Thomas G.", "Tim", "Timothy", "Tito", "Todd", "Tom",
    "Tommy", "Tony", "Travis", "Trent", "Trevor", "Troy", "Ty",
    "Tyler", "Wade", "Wallace", "Wally", "Walt", "Walter", "Ward",
    "Warren", "Wayne", "Vernon", "Wes", "Wesley", "Vic", "Victor",
    "Wilbur", "Will", "Willard", "William", "Willie", "Vin",
    "Vince", "Vincent", "Woodrow", "Zach"
  ].forEach(function(name) {
    db.run(
      "INSERT OR IGNORE INTO name ( name, type )\
       VALUES (?, ?)",
      [name, "firstname"]);
  });
}
